### PR TITLE
CE-2284 - Decode payload if required

### PR DESCRIPTION
**Pull request by Evildethow**
@aheritier @Dohbedoh @PierreBtz to review

### CODE REVIEW

**Review by aheritier — APPROVED** [review]
LGTM 🐝

**Comment by michaelneale** [comment]
seems reasonable to me - not sure what is putting payload= in there though...

**Comment by michaelneale** [comment]
and @bwalding @mpailloncy should I delete my "upstream" repo and make this the canonical one now? 
(also I can add CI to this one too if you like)

**Comment by bwalding** [comment]
Yes - I think that would be the best option.

**Comment by michaelneale** [comment]
@bwalding you don't happen to know if this repo is the one actually running now? as there were a few old commits that made it over to the upstream one, and @Evildethow isn't sure if they are here as well (looks like they probably are).

**Comment by Evildethow** [comment]
We need to pull this one in https://github.com/michaelneale/webhook-relay-plugin/pull/18 for @Dohbedoh

**Comment by bwalding** [comment]
No I don't know - I'll let my uber-hacker @mpailloncy review the diff - https://github.com/michaelneale/webhook-relay-plugin/compare/master...cloudbees:master

https://cloudbees.atlassian.net/browse/OPS-5706

**Comment by Dohbedoh** [comment]
nice one @Evildethow. This could well be the root cause of some exception that we see

```
2018-11-20 15:47:06.837+0000 [id=274102]	SEVERE	o.j.p.w.WebhookReceiver#onMessage: Unable to extract info from JSON received. Is it a valid JSON ?
net.sf.json.JSONException: A JSONObject text must begin with '{' at character 0 of 
	at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:499)
	at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:919)
	at net.sf.json.JSONObject._fromString(JSONObject.java:1145)
	at net.sf.json.JSONObject.fromObject(JSONObject.java:162)
	at net.sf.json.JSONObject.fromObject(JSONObject.java:132)
	at org.jenkinsci.plugins.webhookrelay.WebhookReceiver.onMessage(WebhookReceiver.java:80)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
	at java.lang.Thread.run(Thread.java:748)
```

I am trying to capture the payloads in Elroy. Although not all payload are encoded and I am not sure which one and why...

**Comment by Evildethow** [comment]
@Dohbedoh it fixes what was reported in https://cloudbees.zendesk.com/agent/tickets/66991 and https://cloudbees.atlassian.net/browse/CE-2284

```
payload=SOME_URL_ENCODED_JSON_HERE
```

I doubt it fixes all the issues we are seeing, but it's a start.

**Comment by mpailloncy** [comment]
This repo is the one used to build the plugin installed on Gauntlet masters.

@michaelneale I think old commits you mentioned are [this one](https://github.com/michaelneale/webhook-relay-plugin/commit/9012538f18994568afa8cdac8d27e3379cef155a) + associated merge commit on master. If yes, this commit has already been applied through [this PR](https://github.com/cloudbees/webhook-relay-plugin/pull/2/commits) by @Dohbedoh 

So yes, I think you can delete the upstream residing in your account.

Moreover, we already have a [CI build for the plugin in jenkins-ops ](https://jenkins-ops.cloudbees.com/job/ecs-apps/job/webhook-relay/job/webhook-relay-plugin/) - a build for some previous PRs has been triggered but not this one (I just triggered a "Scan repo" from the multibranch job) - I'll have a look

**Review by mpailloncy — APPROVED** [review]
LGTM

**Comment by mpailloncy** [comment]
The plugin was in a weird state on jenkins-ops since yesterday, preventing it from handling events (the plugin is in version 1.2 but target latest version of the webhook-relay service).
When trying to reconnect (by submitting global Jenkins config without modifications), it has been blocked in this state during few minutes:

> Handling POST /configSubmit from 172.18.64.72 : qtp233530418-2599560
> "Handling POST /configSubmit from 172.18.64.72 : qtp233530418-2599560" Id=2599560 Group=main WAITING on java.util.concurrent.CountDownLatch$Sync@36db3269
> 	at sun.misc.Unsafe.park(Native Method)
> 	-  waiting on java.util.concurrent.CountDownLatch$Sync@36db3269
> 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
> 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
> 	at org.java_websocket.client.WebSocketClient.closeBlocking(WebSocketClient.java:135)
> 	at org.jenkinsci.plugins.webhookrelay.WebsocketHandler.disconnectFromRelay(Handler.kt:27)
> 	at org.jenkinsci.plugins.webhookrelay.WebhookRelayManager.reconnect(WebhookRelayManager.java:28)
> 	at org.jenkinsci.plugins.webhookrelay.WebhookRelayPlugin$WebhookRelayPluginDescriptor.configure(WebhookRelayPlugin.java:58)
> 	at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:3734)
> 	at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:3698)
> 	-  locked hudson.model.Hudson@3aeb1e18

But finally succeeded to disconnect from the relay.

A lot of exceptions like this one have been thrown: 

> Nov 22, 2018 10:52:21 AM SEVERE org.jenkinsci.plugins.webhookrelay.WebhookReceiver onError
> Client error from websocket
> org.java_websocket.exceptions.InvalidFrameException: bad rsv 6
> 	at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:308)
> 	at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:285)
> 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:321)
> 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
> 	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
> 	at java.lang.Thread.run(Thread.java:748)

We need to be able to find the root issue more rapidly. I'll open an OPS ticket on that direction.

@Evildethow I'm going to merge this one and deploy the version to Elroy if that works for you

**Review by PierreBtz — APPROVED** [review]

**Comment by mpailloncy** [comment]
Released in version 1.5 and deployed on Elroy

**Pull request merged**
