### PR TITLE
OPS-3460 - Prevent multiple threads to be created and improve logs for debug

### PR DESCRIPTION
**Pull request by mpailloncy**
Changes : 
- Merge @michaelneale kotlin branch
- "Productionize" the Jenkins plugin 
  - add Jenkinsfile with build/release steps
  - adapt POM to consider this plugin as an internal Cloudbees plugin for now 
- Add some detailed logs (for debug purpose)
- Prevent multiple threads to be created each time we saved Jenkins's global configuration

### CODE REVIEW

**Comment by mpailloncy** [comment]
I followed the latest commits available, which were @michaelneale's kotlin branch. 
Not a problem for me (I like Kotlin!) but no problem to switch back to Java if you think it could be a problem @bwalding @michaelneale

**Comment by mpailloncy** [comment]
To clarify, I don't have done in depth changes for now => my intention is to create a first released version with those changes, test it on jenkins-ops master and see if the problem happens again.

**Review by bwalding — APPROVED** [review]
Looks much better than that "robust code" that @michaelneale wrote!

**Comment by michaelneale** [comment]
@bwalding my code is perfect as always. It is unfortunate that machine architectures as they stand today are not up to the task of my flawless code. 

Besides, if I wasn't spawning all those threads, what would the CPU be doing? UP TO NO GOOD I WOULD SAY ;)

**Comment by bwalding** [comment]
You have met the necessary programming skill requirements to work for Slack!

**Pull request merged**
